name: Verificação padrões de branch
description: Verifica se a branch possui os prefixos padrões de branch

runs:
  using: docker
  image: app/Dockerfile
  # args: # Preciso do nome da branch na passagem?
  #   - ${{ inputs.site }} 
  args:
    - "['bug-', 'projeto-']"
