name: Chamada action compartilhada

on: workflow_dispatch

jobs:
  teste:
    runs-on: windows-latest
    steps:
      - uses: backuplinux-sudo/reutilizaveis/.github/actions/instalacoes@main
        with:
          workflow: ${{ github.workflow }}

