name: Build e Teste

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer o login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Fazer o build e push da imagem
        uses: docker/build-push-action@v6
        with:
          #context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/desafio:latest, ${{ vars.DOCKER_USERNAME }}/desafio:${{ github.sha }}

  teste:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Subir o container
        shell: bash
        run: |
          docker run -d --name desafio -p 8080:80 ${{ vars.DOCKER_USERNAME }}/desafio:${{ github.sha }}
      - name: Testar a aplicação
        shell: bash
        run: |
          sleep 10
          curl -f http://localhost:8080/ || exit 1
