name: Deploy

on: push

jobs:
  deploy_desenvolvimento:
    runs-on: ubuntu-latest
    environment: desenvolvimento
    steps:
      - name: Rodar comandos AWS
        shell: bash
        run: |
          echo << EOF >> teste_desenvolvimento.yaml
            lalala

          EOF
