name: Deploy

on: push

jobs:
  deploy_desenvolvimento:
    runs-on: ubuntu-latest
    environment: desenvolvimento
    steps:
      - name: Gerar arquivo
        shell: bash
        run: |
          cat << EOF >> config_desenvolvimento.yaml
          maquina: ${{ vars.maquina }}
          url: ${{ vars.link }}
          tags:
            name: site-agendamentos
            environment: desenvolvimento

          EOF

          cat config_desenvolvimento.yaml

  deploy_producao:
    runs-on: ubuntu-latest
    environment: producao
    steps:
      - name: Gerar arquivo
        shell: bash
        run: |
          cat << EOF >> config_producao.yaml
          maquina: ${{ vars.maquina }}
          url: ${{ vars.link }}
          tags:
            name: site-agendamentos
            environment: producao

          EOF

          cat config_producao.yaml
