name: Deploy

on: push

jobs:
  deploy_desenvolvimento:
    runs-on: ubuntu-latest
    environment: desenvolvimento
    steps:
      - name: Gerar arquivo
        shell: bash
        run: |
          cat << EOF >> config_desenvolvimento.yaml
          maquina: ${{ vars.maquina }}
          url: ${{ vars.link }}
          tags:
            name: site-agendamentos
            environment: desenvolvimento
            usuario: ${{ vars.usuario }}
            centro_custo: ${{ vars.centro_custo }}

          EOF

          cat config_desenvolvimento.yaml

  deploy_producao:
    runs-on: ubuntu-latest
    environment: producao
    steps:
      - name: Gerar arquivo
        shell: bash
        run: |
          cat << EOF >> config_producao.yaml
          maquina: ${{ vars.maquina }}
          url: ${{ vars.link }}
          tags:
            name: site-agendamentos
            environment: producao
            usuario: ${{ vars.usuario }}
            centro_custo: ${{ vars.centro_custo }}

          EOF

          cat config_producao.yaml
  
  sem_environment:
    runs-on: ubuntu-latest
    steps:
      - name: teste sem environment
        shell: bash
        run: |
          echo usuario=${{ vars.usuario }}
          echo centro_custo=${{ vars.centro_custo }}
