name: Deploy

on:
  workflow_dispatch:
    inputs:
      fruta:
        required: true
        type: choice
        options:
          - abacaxi
          - morango
          - pitanga
          - goiaba
        default: pitanga

jobs:
  teste_input:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir inputs
        run: |
          echo fruta=${{ inputs.fruta }}
          exit 1
      - name: frutas vermelhas
        if: ${{ inputs.fruta != 'abacaxi' }}
        run: |
          echo "Pode ir em sabores de frutas vermelhas"
      - name: teste failure
        if: failure()
        run: echo "executou mesmo com falha"
  condicional:
    runs-on: ubuntu-latest
    if: ${{ inputs.fruta == 'abacaxi' }}
    steps:
      - name: cor
        run: echo "Essa é uma fruta amarela"
