name: Deploy

on: push

jobs:
  deploy_desenvolvimento:
    runs-on: ubuntu-latest
    environment: desenvolvimento
    steps:
      - name: Rodar comandos AWS
        shell: bash
        run: |
          # echo << EOF >> teste_${{ job.deploy_desenvolvimento.environment }}.yaml

          # EOF

          echo environment_job=${{ job.deploy_desenvolvimento.environment }}