name: Deploy

on: push

jobs:
  deploy_desenvolvimento:
    runs-on: ubuntu-latest
    environment: desenvolvimento
    steps:
      - name: Rodar comandos AWS
        shell: bash
        run: |
          echo url=${{ vars.link }}
          # comando ec2
          # comando route 53