name: Deploy

on:
  workflow_dispatch:
    inputs:
      fruta:
        required: true
        type: choice
        options:
          - abacaxi
          - morango
          - pitanga
          - goiaba
        default: pitanga

jobs:
  teste_input:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir inputs
        run: |
          echo fruta=${{ inputs.fruta }}
      - name: frutas vermelhas
        if: ${{ inputs.fruta != 'abacaxi' }}
        run: |
          echo "Pode ir em sabores de frutas vermelhas"
