name: Deploy

on: push

jobs:
  deploy_desenvolvimento:
    runs-on: ubuntu-latest
    environment: desenvolvimento
    steps:
      - name: Rodar comandos AWS
        shell: bash
        run: |
          cat << EOF >> teste_desenvolvimento.yaml
          instance: m5a.xlarge # dica: m5a.large para dev
          url: ${{ vars.url }}
          tags:
            name: site-${{ matrix.environment }}
            enrironment: ${{ matrix.environment }}

          EOF


          cat teste_desenvolvimento.yaml