name: Chamada docker action

on: 
  workflow_dispatch:
    inputs:
      site:
        required: true
        type: string


jobs:
  status_code:
    runs-on: ubuntu-latest
    steps:
      - uses: backuplinux-sudo/action_status_code@main
        with:
          site: ${{ inputs.site }}

  # outputs:
  #   needs: usando_curl
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "A retorno foi ${{ needs.usando_curl.outputs.codigo_retorno }}"
